import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body>
        <body>
          <nav className="nav-bar">
            <div className="nav-content">
              <Link
                href="/"
                className="nav-logo"
              >
                🌸 Tiệm Hoa Vũng Tàu
              </Link>

              <div className="nav-links">
                <Link
                  href="/hoa-sinh-nhat"
                  className="nav-link-item"
                >
                  Hoa sinh nhật
                </Link>
                <Link
                  href="/hoa-8-3"
                  className="nav-link-item"
                >
                  Hoa 8/3
                </Link>
                <Link
                  href="/hoa-tiec"
                  className="nav-link-item"
                >
                  Hoa tiệc
                </Link>
                <Link
                  href="/hoa-valentine"
                  className="nav-link-item"
                >
                  Hoa Valentine
                </Link>
              </div>

              {/* Nút giả lập để giao diện cân đối */}
              <button className="hidden md:block px-4 py-2 text-sm font-semibold text-white bg-slate-600 rounded-full hover:bg-rose-700 transition-all">
                Liên hệ ngay
              </button>
            </div>
          </nav>
          {children}
        </body>
      </body>
    </html>
  );
}
